//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace BankManagement.Models
{
    
    


    public partial class Customer
    {
        public int CustomerNo { get; set; }

        [Required(ErrorMessage = "Please Enter Name")]
        [RegularExpression(@"^[A-Za-z ]*$", ErrorMessage = "Only Alphabets allowed")]
        public string CustomerName { get; set; }

        [Required(ErrorMessage = "Please Enter Valid Phone Number")]
        public string PhoneNo { get; set; }

        [Required(ErrorMessage = "DOB Cant Be Empty")]
        public string DateOfBirth { get; set; }
        public string Address { get; set; }

        [Required(ErrorMessage = "Please Enter Valid Email")]
        [EmailAddress]
        public string Email { get; set; }

        [Required(ErrorMessage = "Please Enter Policy Number")]
        public Nullable<int> PolicyNo { get; set; }
        public string Photo { get; set; }
    
        public virtual PolicyDetail PolicyDetail { get; set; }
    }
}
