//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day6EFDBDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long productId { get; set; }
        public string productName { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> dateOfPurchase { get; set; }
        public string availabilityStatus { get; set; }
        public Nullable<long> categoryId { get; set; }
        public Nullable<long> brandId { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
    }
}
